name: Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false # 允許重新執行失敗的 job
      matrix:
        max-runs: 10   # 最多重新執行次數，你可以根據需要調整
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: npm run build